class Texts {
    var helloTxt = "Witamy w systemie logowania.\n"
    var userHint = "Proszę wybrać jedną z poniższych opcji aby kontynuować:"
    var loginTxt = "Wprowadż login:"
    var passwordTxt = "Wprowadż hasło:"
    var goodCredential = "Zalogowano."
    var badCredential = "Nie poprawny login lub hasło!"
    var createAccountAnswer = "Utworzyć nowe konto?(Y/N)"
    var createAccountYes = "Witamy w systemie rejestracji."
    var goodBay = "Do zobaczenia nastepnym razem."
    var createAccountLogin = "Proszę podać login:"
    var createAccountPassword = "Proszę podać hasło:"
    var createAccountFinish = "Konto zostało dodane, program zostanie za chwile ponownie uruchomiony."
    var dataFileError = "Uszkodzony plik z danymi!"
    var newDataFileQuestion = "Wygenerować nowy plik, wszystie wprowadzone wcześniej dane zostaną utracone?(Y/N)"
    var createAccountFailure = "Nie udało się utworzyć konta, jeden lub więcej warunków nie zostało spełnionych:"
    var loginOccupiedTxt = "login jest już zajęty!"
    var lackBigLetterInPass = "hasło nie zawiera dużej litery!"
    var lackSmallLetterInPass = "hasło nie zawiera małej litery!"
    var lackDigitInPass = "hasło nie zawiera cyfry!"
    var passToShort = "hasło musi zawierać minimum 8 znaków!"
    var passwordHint = "Hasło musi mieć długość minimum 8 znaków oraz składać się małych liter, dużych liter oraz cyfr."
    var signInTxt = "Zaloguj się."
    var exitProgram = "Zamknij program"
}